use anyhow::Result;
use rodio::{OutputStream, OutputStreamHandle, Sink};
use std::collections::HashMap;
use std::io::Cursor;
use std::sync::{Arc, Mutex};

// Generated by build.rs — maps note names to embedded WAV bytes
include!(concat!(env!("OUT_DIR"), "/sample_bank.rs"));

struct SampleBank {
    samples: HashMap<String, &'static [u8]>,
}

impl SampleBank {
    fn new() -> Self {
        Self {
            samples: build_sample_bank(),
        }
    }

    fn get(&self, note: &str) -> Option<&'static [u8]> {
        if let Some(data) = self.samples.get(note) {
            return Some(data);
        }
        // Handle sharp→flat enharmonic: C#4 → Db4
        let normalized = normalize_note(note);
        self.samples.get(&normalized).copied()
    }
}

/// Normalize sharp notes to flat equivalents
fn normalize_note(note: &str) -> String {
    let sharp_to_flat = [
        ("C#", "Db"),
        ("D#", "Eb"),
        ("E#", "F"),
        ("F#", "Gb"),
        ("G#", "Ab"),
        ("A#", "Bb"),
        ("B#", "C"),
    ];
    for (sharp, flat) in &sharp_to_flat {
        if note.starts_with(sharp) {
            return note.replace(sharp, flat);
        }
    }
    note.to_string()
}

pub struct AudioPlayer {
    _stream: OutputStream,
    stream_handle: OutputStreamHandle,
    current_sink: Arc<Mutex<Option<Sink>>>,
    sample_bank: SampleBank,
}

impl AudioPlayer {
    pub fn new() -> Result<Self> {
        let (stream, stream_handle) = OutputStream::try_default()?;
        Ok(Self {
            _stream: stream,
            stream_handle,
            current_sink: Arc::new(Mutex::new(None)),
            sample_bank: SampleBank::new(),
        })
    }

    pub fn play_note(&self, note: &str) -> Result<()> {
        let data = match self.sample_bank.get(note) {
            Some(d) => d,
            None => {
                // Fallback to C4
                match self.sample_bank.get("C4") {
                    Some(d) => d,
                    None => return Ok(()),
                }
            }
        };

        // Stop previous note
        {
            let mut current = self.current_sink.lock().unwrap();
            if let Some(old_sink) = current.take() {
                old_sink.stop();
            }
        }

        let sink = Sink::try_new(&self.stream_handle)?;
        let cursor = Cursor::new(data);
        let source = rodio::Decoder::new(cursor)?;
        sink.append(source);

        {
            let mut current = self.current_sink.lock().unwrap();
            *current = Some(sink);
        }

        Ok(())
    }
}
