use anyhow::Result;
use rodio::{OutputStream, OutputStreamHandle, Sink};
use std::collections::HashMap;
use std::io::Cursor;
use std::sync::{Arc, Mutex};

// Generated by build.rs — maps note names to embedded WAV bytes
include!(concat!(env!("OUT_DIR"), "/sample_bank.rs"));

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SoundType {
    Rhodes,
    Piano,
}

impl std::fmt::Display for SoundType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SoundType::Rhodes => write!(f, "rhodes"),
            SoundType::Piano => write!(f, "piano"),
        }
    }
}

impl std::str::FromStr for SoundType {
    type Err = String;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "rhodes" => Ok(SoundType::Rhodes),
            "piano" => Ok(SoundType::Piano),
            _ => Err(format!("unknown sound type: {s} (expected 'rhodes' or 'piano')")),
        }
    }
}

struct SampleBank {
    samples: HashMap<String, &'static [u8]>,
}

impl SampleBank {
    fn rhodes() -> Self {
        Self {
            samples: build_rhodes_bank(),
        }
    }

    fn piano() -> Self {
        Self {
            samples: build_piano_bank(),
        }
    }

    fn get(&self, note: &str) -> Option<&'static [u8]> {
        if let Some(data) = self.samples.get(note) {
            return Some(data);
        }
        // Handle sharp→flat enharmonic: C#4 → Db4
        let normalized = normalize_note(note);
        self.samples.get(&normalized).copied()
    }
}

/// Normalize sharp notes to flat equivalents
fn normalize_note(note: &str) -> String {
    let sharp_to_flat = [
        ("C#", "Db"),
        ("D#", "Eb"),
        ("E#", "F"),
        ("F#", "Gb"),
        ("G#", "Ab"),
        ("A#", "Bb"),
        ("B#", "C"),
    ];
    for (sharp, flat) in &sharp_to_flat {
        if note.starts_with(sharp) {
            return note.replace(sharp, flat);
        }
    }
    note.to_string()
}

pub struct AudioPlayer {
    _stream: OutputStream,
    stream_handle: OutputStreamHandle,
    current_sink: Arc<Mutex<Option<Sink>>>,
    rhodes_bank: SampleBank,
    piano_bank: SampleBank,
    sound_type: Arc<Mutex<SoundType>>,
}

impl AudioPlayer {
    pub fn new() -> Result<Self> {
        let (stream, stream_handle) = OutputStream::try_default()?;
        Ok(Self {
            _stream: stream,
            stream_handle,
            current_sink: Arc::new(Mutex::new(None)),
            rhodes_bank: SampleBank::rhodes(),
            piano_bank: SampleBank::piano(),
            sound_type: Arc::new(Mutex::new(SoundType::Rhodes)),
        })
    }

    /// Get a cloneable handle to the sound type for sharing across threads.
    pub fn sound_type_handle(&self) -> Arc<Mutex<SoundType>> {
        Arc::clone(&self.sound_type)
    }

    pub fn sound_type(&self) -> SoundType {
        *self.sound_type.lock().unwrap()
    }

    fn current_bank(&self) -> &SampleBank {
        match *self.sound_type.lock().unwrap() {
            SoundType::Rhodes => &self.rhodes_bank,
            SoundType::Piano => &self.piano_bank,
        }
    }

    pub fn play_note(&self, note: &str) -> Result<()> {
        let bank = self.current_bank();
        let data = match bank.get(note) {
            Some(d) => d,
            None => {
                // Fallback to C4
                match bank.get("C4") {
                    Some(d) => d,
                    None => return Ok(()),
                }
            }
        };

        // Stop previous note
        {
            let mut current = self.current_sink.lock().unwrap();
            if let Some(old_sink) = current.take() {
                old_sink.stop();
            }
        }

        let sink = Sink::try_new(&self.stream_handle)?;
        let cursor = Cursor::new(data);
        let source = rodio::Decoder::new(cursor)?;
        sink.append(source);

        {
            let mut current = self.current_sink.lock().unwrap();
            *current = Some(sink);
        }

        Ok(())
    }
}
